version: "3.6"

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: postgres

  api:
    <<: &app
      build: .
      # env_file: .env
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_HOST: localhost
      volumes:
      - .:/app
      depends_on:
      - db
    ports:
    - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]